/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WShopsRouteImport } from './routes/w/shops'
import { Route as WRegisterRouteImport } from './routes/w/register'
import { Route as WProfileRouteImport } from './routes/w/profile'
import { Route as WDashboardRouteImport } from './routes/w/dashboard'
import { Route as WContactsRouteImport } from './routes/w/contacts'
import { Route as SWorkersRouteImport } from './routes/s/workers'
import { Route as SRegisterRouteImport } from './routes/s/register'
import { Route as SProfileRouteImport } from './routes/s/profile'
import { Route as SProductsRouteImport } from './routes/s/products'
import { Route as SDashboardRouteImport } from './routes/s/dashboard'
import { Route as SContactsRouteImport } from './routes/s/contacts'
import { Route as CWorkersRouteImport } from './routes/c/workers'
import { Route as CShopsRouteImport } from './routes/c/shops'
import { Route as CRegisterRouteImport } from './routes/c/register'
import { Route as CProfileRouteImport } from './routes/c/profile'
import { Route as CHomeRouteImport } from './routes/c/home'
import { Route as WShopIdRouteImport } from './routes/w/shop.$id'
import { Route as SWorkerIdRouteImport } from './routes/s/worker.$id'
import { Route as CWorkerIdRouteImport } from './routes/c/worker.$id'
import { Route as CShopIdRouteImport } from './routes/c/shop.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WShopsRoute = WShopsRouteImport.update({
  id: '/w/shops',
  path: '/w/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const WRegisterRoute = WRegisterRouteImport.update({
  id: '/w/register',
  path: '/w/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WProfileRoute = WProfileRouteImport.update({
  id: '/w/profile',
  path: '/w/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WDashboardRoute = WDashboardRouteImport.update({
  id: '/w/dashboard',
  path: '/w/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WContactsRoute = WContactsRouteImport.update({
  id: '/w/contacts',
  path: '/w/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const SWorkersRoute = SWorkersRouteImport.update({
  id: '/s/workers',
  path: '/s/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SRegisterRoute = SRegisterRouteImport.update({
  id: '/s/register',
  path: '/s/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SProfileRoute = SProfileRouteImport.update({
  id: '/s/profile',
  path: '/s/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SProductsRoute = SProductsRouteImport.update({
  id: '/s/products',
  path: '/s/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SDashboardRoute = SDashboardRouteImport.update({
  id: '/s/dashboard',
  path: '/s/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SContactsRoute = SContactsRouteImport.update({
  id: '/s/contacts',
  path: '/s/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CWorkersRoute = CWorkersRouteImport.update({
  id: '/c/workers',
  path: '/c/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const CShopsRoute = CShopsRouteImport.update({
  id: '/c/shops',
  path: '/c/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const CRegisterRoute = CRegisterRouteImport.update({
  id: '/c/register',
  path: '/c/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CProfileRoute = CProfileRouteImport.update({
  id: '/c/profile',
  path: '/c/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CHomeRoute = CHomeRouteImport.update({
  id: '/c/home',
  path: '/c/home',
  getParentRoute: () => rootRouteImport,
} as any)
const WShopIdRoute = WShopIdRouteImport.update({
  id: '/w/shop/$id',
  path: '/w/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SWorkerIdRoute = SWorkerIdRouteImport.update({
  id: '/s/worker/$id',
  path: '/s/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CWorkerIdRoute = CWorkerIdRouteImport.update({
  id: '/c/worker/$id',
  path: '/c/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CShopIdRoute = CShopIdRouteImport.update({
  id: '/c/shop/$id',
  path: '/c/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/home': typeof CHomeRoute
  '/c/profile': typeof CProfileRoute
  '/c/register': typeof CRegisterRoute
  '/c/shops': typeof CShopsRoute
  '/c/workers': typeof CWorkersRoute
  '/s/contacts': typeof SContactsRoute
  '/s/dashboard': typeof SDashboardRoute
  '/s/products': typeof SProductsRoute
  '/s/profile': typeof SProfileRoute
  '/s/register': typeof SRegisterRoute
  '/s/workers': typeof SWorkersRoute
  '/w/contacts': typeof WContactsRoute
  '/w/dashboard': typeof WDashboardRoute
  '/w/profile': typeof WProfileRoute
  '/w/register': typeof WRegisterRoute
  '/w/shops': typeof WShopsRoute
  '/c/shop/$id': typeof CShopIdRoute
  '/c/worker/$id': typeof CWorkerIdRoute
  '/s/worker/$id': typeof SWorkerIdRoute
  '/w/shop/$id': typeof WShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/home': typeof CHomeRoute
  '/c/profile': typeof CProfileRoute
  '/c/register': typeof CRegisterRoute
  '/c/shops': typeof CShopsRoute
  '/c/workers': typeof CWorkersRoute
  '/s/contacts': typeof SContactsRoute
  '/s/dashboard': typeof SDashboardRoute
  '/s/products': typeof SProductsRoute
  '/s/profile': typeof SProfileRoute
  '/s/register': typeof SRegisterRoute
  '/s/workers': typeof SWorkersRoute
  '/w/contacts': typeof WContactsRoute
  '/w/dashboard': typeof WDashboardRoute
  '/w/profile': typeof WProfileRoute
  '/w/register': typeof WRegisterRoute
  '/w/shops': typeof WShopsRoute
  '/c/shop/$id': typeof CShopIdRoute
  '/c/worker/$id': typeof CWorkerIdRoute
  '/s/worker/$id': typeof SWorkerIdRoute
  '/w/shop/$id': typeof WShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/home': typeof CHomeRoute
  '/c/profile': typeof CProfileRoute
  '/c/register': typeof CRegisterRoute
  '/c/shops': typeof CShopsRoute
  '/c/workers': typeof CWorkersRoute
  '/s/contacts': typeof SContactsRoute
  '/s/dashboard': typeof SDashboardRoute
  '/s/products': typeof SProductsRoute
  '/s/profile': typeof SProfileRoute
  '/s/register': typeof SRegisterRoute
  '/s/workers': typeof SWorkersRoute
  '/w/contacts': typeof WContactsRoute
  '/w/dashboard': typeof WDashboardRoute
  '/w/profile': typeof WProfileRoute
  '/w/register': typeof WRegisterRoute
  '/w/shops': typeof WShopsRoute
  '/c/shop/$id': typeof CShopIdRoute
  '/c/worker/$id': typeof CWorkerIdRoute
  '/s/worker/$id': typeof SWorkerIdRoute
  '/w/shop/$id': typeof WShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/home'
    | '/c/profile'
    | '/c/register'
    | '/c/shops'
    | '/c/workers'
    | '/s/contacts'
    | '/s/dashboard'
    | '/s/products'
    | '/s/profile'
    | '/s/register'
    | '/s/workers'
    | '/w/contacts'
    | '/w/dashboard'
    | '/w/profile'
    | '/w/register'
    | '/w/shops'
    | '/c/shop/$id'
    | '/c/worker/$id'
    | '/s/worker/$id'
    | '/w/shop/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/home'
    | '/c/profile'
    | '/c/register'
    | '/c/shops'
    | '/c/workers'
    | '/s/contacts'
    | '/s/dashboard'
    | '/s/products'
    | '/s/profile'
    | '/s/register'
    | '/s/workers'
    | '/w/contacts'
    | '/w/dashboard'
    | '/w/profile'
    | '/w/register'
    | '/w/shops'
    | '/c/shop/$id'
    | '/c/worker/$id'
    | '/s/worker/$id'
    | '/w/shop/$id'
  id:
    | '__root__'
    | '/'
    | '/c/home'
    | '/c/profile'
    | '/c/register'
    | '/c/shops'
    | '/c/workers'
    | '/s/contacts'
    | '/s/dashboard'
    | '/s/products'
    | '/s/profile'
    | '/s/register'
    | '/s/workers'
    | '/w/contacts'
    | '/w/dashboard'
    | '/w/profile'
    | '/w/register'
    | '/w/shops'
    | '/c/shop/$id'
    | '/c/worker/$id'
    | '/s/worker/$id'
    | '/w/shop/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CHomeRoute: typeof CHomeRoute
  CProfileRoute: typeof CProfileRoute
  CRegisterRoute: typeof CRegisterRoute
  CShopsRoute: typeof CShopsRoute
  CWorkersRoute: typeof CWorkersRoute
  SContactsRoute: typeof SContactsRoute
  SDashboardRoute: typeof SDashboardRoute
  SProductsRoute: typeof SProductsRoute
  SProfileRoute: typeof SProfileRoute
  SRegisterRoute: typeof SRegisterRoute
  SWorkersRoute: typeof SWorkersRoute
  WContactsRoute: typeof WContactsRoute
  WDashboardRoute: typeof WDashboardRoute
  WProfileRoute: typeof WProfileRoute
  WRegisterRoute: typeof WRegisterRoute
  WShopsRoute: typeof WShopsRoute
  CShopIdRoute: typeof CShopIdRoute
  CWorkerIdRoute: typeof CWorkerIdRoute
  SWorkerIdRoute: typeof SWorkerIdRoute
  WShopIdRoute: typeof WShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/shops': {
      id: '/w/shops'
      path: '/w/shops'
      fullPath: '/w/shops'
      preLoaderRoute: typeof WShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/register': {
      id: '/w/register'
      path: '/w/register'
      fullPath: '/w/register'
      preLoaderRoute: typeof WRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/profile': {
      id: '/w/profile'
      path: '/w/profile'
      fullPath: '/w/profile'
      preLoaderRoute: typeof WProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/dashboard': {
      id: '/w/dashboard'
      path: '/w/dashboard'
      fullPath: '/w/dashboard'
      preLoaderRoute: typeof WDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/contacts': {
      id: '/w/contacts'
      path: '/w/contacts'
      fullPath: '/w/contacts'
      preLoaderRoute: typeof WContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/workers': {
      id: '/s/workers'
      path: '/s/workers'
      fullPath: '/s/workers'
      preLoaderRoute: typeof SWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/register': {
      id: '/s/register'
      path: '/s/register'
      fullPath: '/s/register'
      preLoaderRoute: typeof SRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/profile': {
      id: '/s/profile'
      path: '/s/profile'
      fullPath: '/s/profile'
      preLoaderRoute: typeof SProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/products': {
      id: '/s/products'
      path: '/s/products'
      fullPath: '/s/products'
      preLoaderRoute: typeof SProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/dashboard': {
      id: '/s/dashboard'
      path: '/s/dashboard'
      fullPath: '/s/dashboard'
      preLoaderRoute: typeof SDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/contacts': {
      id: '/s/contacts'
      path: '/s/contacts'
      fullPath: '/s/contacts'
      preLoaderRoute: typeof SContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/workers': {
      id: '/c/workers'
      path: '/c/workers'
      fullPath: '/c/workers'
      preLoaderRoute: typeof CWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/shops': {
      id: '/c/shops'
      path: '/c/shops'
      fullPath: '/c/shops'
      preLoaderRoute: typeof CShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/register': {
      id: '/c/register'
      path: '/c/register'
      fullPath: '/c/register'
      preLoaderRoute: typeof CRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/profile': {
      id: '/c/profile'
      path: '/c/profile'
      fullPath: '/c/profile'
      preLoaderRoute: typeof CProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/home': {
      id: '/c/home'
      path: '/c/home'
      fullPath: '/c/home'
      preLoaderRoute: typeof CHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/shop/$id': {
      id: '/w/shop/$id'
      path: '/w/shop/$id'
      fullPath: '/w/shop/$id'
      preLoaderRoute: typeof WShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/worker/$id': {
      id: '/s/worker/$id'
      path: '/s/worker/$id'
      fullPath: '/s/worker/$id'
      preLoaderRoute: typeof SWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/worker/$id': {
      id: '/c/worker/$id'
      path: '/c/worker/$id'
      fullPath: '/c/worker/$id'
      preLoaderRoute: typeof CWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/shop/$id': {
      id: '/c/shop/$id'
      path: '/c/shop/$id'
      fullPath: '/c/shop/$id'
      preLoaderRoute: typeof CShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CHomeRoute: CHomeRoute,
  CProfileRoute: CProfileRoute,
  CRegisterRoute: CRegisterRoute,
  CShopsRoute: CShopsRoute,
  CWorkersRoute: CWorkersRoute,
  SContactsRoute: SContactsRoute,
  SDashboardRoute: SDashboardRoute,
  SProductsRoute: SProductsRoute,
  SProfileRoute: SProfileRoute,
  SRegisterRoute: SRegisterRoute,
  SWorkersRoute: SWorkersRoute,
  WContactsRoute: WContactsRoute,
  WDashboardRoute: WDashboardRoute,
  WProfileRoute: WProfileRoute,
  WRegisterRoute: WRegisterRoute,
  WShopsRoute: WShopsRoute,
  CShopIdRoute: CShopIdRoute,
  CWorkerIdRoute: CWorkerIdRoute,
  SWorkerIdRoute: SWorkerIdRoute,
  WShopIdRoute: WShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
