// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function readEnv(name: string) {
  return (
    (import.meta.env[name] as string | undefined) ||
    (import.meta.env[name.replace("SUPABASE", "SUPBASE")] as string | undefined)
  );
}

function createSupabaseClient() {
  const SUPABASE_URL = readEnv("VITE_SUPABASE_URL") || "https://placeholder-necto.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    readEnv("VITE_SUPABASE_PUBLISHABLE_KEY") || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy_key";

  if (!readEnv("VITE_SUPABASE_URL") || !readEnv("VITE_SUPABASE_PUBLISHABLE_KEY")) {
    console.warn(
      "[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using mock placeholder endpoint. Configure these in your settings/environment to connect to live Supabase.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
